// Auto-generated by packet_gen.py. DO NOT EDIT!
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;

namespace Blocks.Network
{
    public enum PacketId : uint
    {
        Connect = 1,
        Disconnect = 2,
        SetPosition = 3,
        Move = 4,
        Attack = 5,
    }

    public static class PacketHelper
    {
        public static string ReadPacketString(BinaryReader reader)
        {
            ushort len = reader.ReadUInt16();
            byte[] bytes = reader.ReadBytes(len);
            return Encoding.UTF8.GetString(bytes);
        }

        public static void WritePacketString(BinaryWriter writer, string str)
        {
            str ??= string.Empty;
            byte[] bytes = Encoding.UTF8.GetBytes(str);
            writer.Write((ushort)bytes.Length);
            writer.Write(bytes);
        }
    }

    public class C2S_Connect
    {
        public const uint ID = 1;

        public string username = string.Empty;

        public byte[] Serialize()
        {
            using var bodyMs = new MemoryStream();
            using var bodyWriter = new BinaryWriter(bodyMs);
            PacketHelper.WritePacketString(bodyWriter, username);

            byte[] bodyBytes = bodyMs.ToArray();
            uint packetSize = (uint)(8 + bodyBytes.Length);

            using var packetMs = new MemoryStream();
            using var packetWriter = new BinaryWriter(packetMs);
            packetWriter.Write(ID);
            packetWriter.Write(packetSize);
            packetWriter.Write(bodyBytes);
            return packetMs.ToArray();
        }

        public static C2S_Connect Deserialize(BinaryReader reader)
        {
            var packet = new C2S_Connect();
            packet.username = PacketHelper.ReadPacketString(reader);
            return packet;
        }

        public static C2S_Connect Deserialize(byte[] payload, int offset = 0, int length = -1)
        {
            if (length < 0) length = payload.Length - offset;
            using var ms = new MemoryStream(payload, offset, length);
            using var reader = new BinaryReader(ms);
            return Deserialize(reader);
        }
    }

    public class S2C_Connect
    {
        public const uint ID = 1;

        public int userid = 0;
        public string username = string.Empty;
        public bool is_other_user = false;

        public byte[] Serialize()
        {
            using var bodyMs = new MemoryStream();
            using var bodyWriter = new BinaryWriter(bodyMs);
            bodyWriter.Write(userid);
            PacketHelper.WritePacketString(bodyWriter, username);
            bodyWriter.Write(is_other_user);

            byte[] bodyBytes = bodyMs.ToArray();
            uint packetSize = (uint)(8 + bodyBytes.Length);

            using var packetMs = new MemoryStream();
            using var packetWriter = new BinaryWriter(packetMs);
            packetWriter.Write(ID);
            packetWriter.Write(packetSize);
            packetWriter.Write(bodyBytes);
            return packetMs.ToArray();
        }

        public static S2C_Connect Deserialize(BinaryReader reader)
        {
            var packet = new S2C_Connect();
            packet.userid = reader.ReadInt32();
            packet.username = PacketHelper.ReadPacketString(reader);
            packet.is_other_user = reader.ReadBoolean();
            return packet;
        }

        public static S2C_Connect Deserialize(byte[] payload, int offset = 0, int length = -1)
        {
            if (length < 0) length = payload.Length - offset;
            using var ms = new MemoryStream(payload, offset, length);
            using var reader = new BinaryReader(ms);
            return Deserialize(reader);
        }
    }

    public class C2S_Disconnect
    {
        public const uint ID = 2;


        public byte[] Serialize()
        {
            uint packetSize = 8;
            using var packetMs = new MemoryStream();
            using var packetWriter = new BinaryWriter(packetMs);
            packetWriter.Write(ID);
            packetWriter.Write(packetSize);
            return packetMs.ToArray();
        }

        public static C2S_Disconnect Deserialize(BinaryReader reader)
        {
            return new C2S_Disconnect();
        }

        public static C2S_Disconnect Deserialize(byte[] payload, int offset = 0, int length = -1)
        {
            return new C2S_Disconnect();
        }
    }

    public class S2C_Disconnect
    {
        public const uint ID = 2;

        public int userid = 0;
        public string reason = string.Empty;

        public byte[] Serialize()
        {
            using var bodyMs = new MemoryStream();
            using var bodyWriter = new BinaryWriter(bodyMs);
            bodyWriter.Write(userid);
            PacketHelper.WritePacketString(bodyWriter, reason);

            byte[] bodyBytes = bodyMs.ToArray();
            uint packetSize = (uint)(8 + bodyBytes.Length);

            using var packetMs = new MemoryStream();
            using var packetWriter = new BinaryWriter(packetMs);
            packetWriter.Write(ID);
            packetWriter.Write(packetSize);
            packetWriter.Write(bodyBytes);
            return packetMs.ToArray();
        }

        public static S2C_Disconnect Deserialize(BinaryReader reader)
        {
            var packet = new S2C_Disconnect();
            packet.userid = reader.ReadInt32();
            packet.reason = PacketHelper.ReadPacketString(reader);
            return packet;
        }

        public static S2C_Disconnect Deserialize(byte[] payload, int offset = 0, int length = -1)
        {
            if (length < 0) length = payload.Length - offset;
            using var ms = new MemoryStream(payload, offset, length);
            using var reader = new BinaryReader(ms);
            return Deserialize(reader);
        }
    }

    public class C2S_SetPosition
    {
        public const uint ID = 3;

        public double x = 0.0;
        public double y = 0.0;
        public bool facing_right = false;
        public bool reset_velocity = false;

        public byte[] Serialize()
        {
            using var bodyMs = new MemoryStream();
            using var bodyWriter = new BinaryWriter(bodyMs);
            bodyWriter.Write(x);
            bodyWriter.Write(y);
            bodyWriter.Write(facing_right);
            bodyWriter.Write(reset_velocity);

            byte[] bodyBytes = bodyMs.ToArray();
            uint packetSize = (uint)(8 + bodyBytes.Length);

            using var packetMs = new MemoryStream();
            using var packetWriter = new BinaryWriter(packetMs);
            packetWriter.Write(ID);
            packetWriter.Write(packetSize);
            packetWriter.Write(bodyBytes);
            return packetMs.ToArray();
        }

        public static C2S_SetPosition Deserialize(BinaryReader reader)
        {
            var packet = new C2S_SetPosition();
            packet.x = reader.ReadDouble();
            packet.y = reader.ReadDouble();
            packet.facing_right = reader.ReadBoolean();
            packet.reset_velocity = reader.ReadBoolean();
            return packet;
        }

        public static C2S_SetPosition Deserialize(byte[] payload, int offset = 0, int length = -1)
        {
            if (length < 0) length = payload.Length - offset;
            using var ms = new MemoryStream(payload, offset, length);
            using var reader = new BinaryReader(ms);
            return Deserialize(reader);
        }
    }

    public class S2C_SetPosition
    {
        public const uint ID = 3;

        public int userid = 0;
        public double x = 0.0;
        public double y = 0.0;
        public bool facing_right = false;
        public bool reset_velocity = false;

        public byte[] Serialize()
        {
            using var bodyMs = new MemoryStream();
            using var bodyWriter = new BinaryWriter(bodyMs);
            bodyWriter.Write(userid);
            bodyWriter.Write(x);
            bodyWriter.Write(y);
            bodyWriter.Write(facing_right);
            bodyWriter.Write(reset_velocity);

            byte[] bodyBytes = bodyMs.ToArray();
            uint packetSize = (uint)(8 + bodyBytes.Length);

            using var packetMs = new MemoryStream();
            using var packetWriter = new BinaryWriter(packetMs);
            packetWriter.Write(ID);
            packetWriter.Write(packetSize);
            packetWriter.Write(bodyBytes);
            return packetMs.ToArray();
        }

        public static S2C_SetPosition Deserialize(BinaryReader reader)
        {
            var packet = new S2C_SetPosition();
            packet.userid = reader.ReadInt32();
            packet.x = reader.ReadDouble();
            packet.y = reader.ReadDouble();
            packet.facing_right = reader.ReadBoolean();
            packet.reset_velocity = reader.ReadBoolean();
            return packet;
        }

        public static S2C_SetPosition Deserialize(byte[] payload, int offset = 0, int length = -1)
        {
            if (length < 0) length = payload.Length - offset;
            using var ms = new MemoryStream(payload, offset, length);
            using var reader = new BinaryReader(ms);
            return Deserialize(reader);
        }
    }

    public class C2S_Move
    {
        public const uint ID = 4;

        public double x = 0.0;
        public double y = 0.0;
        public double vx = 0.0;
        public double vy = 0.0;
        public bool facing_right = false;

        public byte[] Serialize()
        {
            using var bodyMs = new MemoryStream();
            using var bodyWriter = new BinaryWriter(bodyMs);
            bodyWriter.Write(x);
            bodyWriter.Write(y);
            bodyWriter.Write(vx);
            bodyWriter.Write(vy);
            bodyWriter.Write(facing_right);

            byte[] bodyBytes = bodyMs.ToArray();
            uint packetSize = (uint)(8 + bodyBytes.Length);

            using var packetMs = new MemoryStream();
            using var packetWriter = new BinaryWriter(packetMs);
            packetWriter.Write(ID);
            packetWriter.Write(packetSize);
            packetWriter.Write(bodyBytes);
            return packetMs.ToArray();
        }

        public static C2S_Move Deserialize(BinaryReader reader)
        {
            var packet = new C2S_Move();
            packet.x = reader.ReadDouble();
            packet.y = reader.ReadDouble();
            packet.vx = reader.ReadDouble();
            packet.vy = reader.ReadDouble();
            packet.facing_right = reader.ReadBoolean();
            return packet;
        }

        public static C2S_Move Deserialize(byte[] payload, int offset = 0, int length = -1)
        {
            if (length < 0) length = payload.Length - offset;
            using var ms = new MemoryStream(payload, offset, length);
            using var reader = new BinaryReader(ms);
            return Deserialize(reader);
        }
    }

    public class S2C_Move
    {
        public const uint ID = 4;

        public int userid = 0;
        public double x = 0.0;
        public double y = 0.0;
        public double vx = 0.0;
        public double vy = 0.0;
        public bool facing_right = false;

        public byte[] Serialize()
        {
            using var bodyMs = new MemoryStream();
            using var bodyWriter = new BinaryWriter(bodyMs);
            bodyWriter.Write(userid);
            bodyWriter.Write(x);
            bodyWriter.Write(y);
            bodyWriter.Write(vx);
            bodyWriter.Write(vy);
            bodyWriter.Write(facing_right);

            byte[] bodyBytes = bodyMs.ToArray();
            uint packetSize = (uint)(8 + bodyBytes.Length);

            using var packetMs = new MemoryStream();
            using var packetWriter = new BinaryWriter(packetMs);
            packetWriter.Write(ID);
            packetWriter.Write(packetSize);
            packetWriter.Write(bodyBytes);
            return packetMs.ToArray();
        }

        public static S2C_Move Deserialize(BinaryReader reader)
        {
            var packet = new S2C_Move();
            packet.userid = reader.ReadInt32();
            packet.x = reader.ReadDouble();
            packet.y = reader.ReadDouble();
            packet.vx = reader.ReadDouble();
            packet.vy = reader.ReadDouble();
            packet.facing_right = reader.ReadBoolean();
            return packet;
        }

        public static S2C_Move Deserialize(byte[] payload, int offset = 0, int length = -1)
        {
            if (length < 0) length = payload.Length - offset;
            using var ms = new MemoryStream(payload, offset, length);
            using var reader = new BinaryReader(ms);
            return Deserialize(reader);
        }
    }

    public class C2S_Attack
    {
        public const uint ID = 5;


        public byte[] Serialize()
        {
            uint packetSize = 8;
            using var packetMs = new MemoryStream();
            using var packetWriter = new BinaryWriter(packetMs);
            packetWriter.Write(ID);
            packetWriter.Write(packetSize);
            return packetMs.ToArray();
        }

        public static C2S_Attack Deserialize(BinaryReader reader)
        {
            return new C2S_Attack();
        }

        public static C2S_Attack Deserialize(byte[] payload, int offset = 0, int length = -1)
        {
            return new C2S_Attack();
        }
    }

    public class S2C_Attack
    {
        public const uint ID = 5;

        public int userid = 0;

        public byte[] Serialize()
        {
            using var bodyMs = new MemoryStream();
            using var bodyWriter = new BinaryWriter(bodyMs);
            bodyWriter.Write(userid);

            byte[] bodyBytes = bodyMs.ToArray();
            uint packetSize = (uint)(8 + bodyBytes.Length);

            using var packetMs = new MemoryStream();
            using var packetWriter = new BinaryWriter(packetMs);
            packetWriter.Write(ID);
            packetWriter.Write(packetSize);
            packetWriter.Write(bodyBytes);
            return packetMs.ToArray();
        }

        public static S2C_Attack Deserialize(BinaryReader reader)
        {
            var packet = new S2C_Attack();
            packet.userid = reader.ReadInt32();
            return packet;
        }

        public static S2C_Attack Deserialize(byte[] payload, int offset = 0, int length = -1)
        {
            if (length < 0) length = payload.Length - offset;
            using var ms = new MemoryStream(payload, offset, length);
            using var reader = new BinaryReader(ms);
            return Deserialize(reader);
        }
    }
}
