// Auto-generated by packet_gen.py. DO NOT EDIT!
#ifndef __PACKETS_GENERATED_H__
#define __PACKETS_GENERATED_H__

#include <cstdint>
#include <string>
#include <vector>
#include <span>
#include <cstring>
#include <stdexcept>
#include "packet.h"

namespace Packet
{

class Reader
{
public:
    Reader(std::span<const std::byte> data) : data_(data), offset_(0) {}

    template <typename T>
    T read()
    {
        static_assert(std::is_trivially_copyable_v<T>, "Type must be trivially copyable");
        if (offset_ + sizeof(T) > data_.size())
            throw std::runtime_error("Packet buffer underflow");
        T val;
        std::memcpy(&val, data_.data() + offset_, sizeof(T));
        offset_ += sizeof(T);
        return val;
    }

    std::string read_string()
    {
        uint16_t len = read<uint16_t>();
        if (offset_ + len > data_.size())
            throw std::runtime_error("Packet string underflow");
        std::string str(reinterpret_cast<const char*>(data_.data() + offset_), len);
        offset_ += len;
        return str;
    }

    size_t remaining() const { return data_.size() - offset_; }

private:
    std::span<const std::byte> data_;
    size_t offset_ = 0;
};

class Writer
{
public:
    template <typename T>
    void write(const T& val)
    {
        static_assert(std::is_trivially_copyable_v<T>, "Type must be trivially copyable");
        const auto* ptr = reinterpret_cast<const std::byte*>(&val);
        buffer_.insert(buffer_.end(), ptr, ptr + sizeof(T));
    }

    void write_string(const std::string& str)
    {
        write<uint16_t>(static_cast<uint16_t>(str.size()));
        const auto* ptr = reinterpret_cast<const std::byte*>(str.data());
        buffer_.insert(buffer_.end(), ptr, ptr + str.size());
    }

    void write_raw(const std::vector<std::byte>& raw)
    {
        buffer_.insert(buffer_.end(), raw.begin(), raw.end());
    }

    const std::vector<std::byte>& buffer() const { return buffer_; }
    std::vector<std::byte>& buffer() { return buffer_; }

private:
    std::vector<std::byte> buffer_;
};

struct C2S_Connect
{
    static constexpr uint32_t ID = 1;

    std::string username = "";

    static C2S_Connect deserialize(std::span<const std::byte> payload)
    {
        Reader reader(payload);
        C2S_Connect packet;
        packet.username = reader.read_string();
        return packet;
    }

    std::vector<std::byte> serialize() const
    {
        Writer body;
        body.write_string(username);

        PacketHeader header;
        header.packet_id = ID;
        header.packet_size = static_cast<uint32_t>(sizeof(PacketHeader) + body.buffer().size());

        Writer writer;
        writer.write(header);
        writer.write_raw(body.buffer());
        return writer.buffer();
    }
};
using ConnectClientPacket = C2S_Connect;

struct S2C_Connect
{
    static constexpr uint32_t ID = 1;

    int32_t userid = 0;
    std::string username = "";
    bool is_other_user = false;

    static S2C_Connect deserialize(std::span<const std::byte> payload)
    {
        Reader reader(payload);
        S2C_Connect packet;
        packet.userid = reader.read<int32_t>();
        packet.username = reader.read_string();
        packet.is_other_user = reader.read<bool>();
        return packet;
    }

    std::vector<std::byte> serialize() const
    {
        Writer body;
        body.write<int32_t>(userid);
        body.write_string(username);
        body.write<bool>(is_other_user);

        PacketHeader header;
        header.packet_id = ID;
        header.packet_size = static_cast<uint32_t>(sizeof(PacketHeader) + body.buffer().size());

        Writer writer;
        writer.write(header);
        writer.write_raw(body.buffer());
        return writer.buffer();
    }
};
using ConnectServerPacket = S2C_Connect;

struct C2S_Disconnect
{
    static constexpr uint32_t ID = 2;


    static C2S_Disconnect deserialize([[maybe_unused]] std::span<const std::byte> payload)
    {
        return C2S_Disconnect{};
    }

    std::vector<std::byte> serialize() const
    {
        PacketHeader header;
        header.packet_id = ID;
        header.packet_size = static_cast<uint32_t>(sizeof(PacketHeader));

        Writer writer;
        writer.write(header);
        return writer.buffer();
    }
};
using DisconnectClientPacket = C2S_Disconnect;

struct S2C_Disconnect
{
    static constexpr uint32_t ID = 2;

    int32_t userid = 0;
    std::string reason = "";

    static S2C_Disconnect deserialize(std::span<const std::byte> payload)
    {
        Reader reader(payload);
        S2C_Disconnect packet;
        packet.userid = reader.read<int32_t>();
        packet.reason = reader.read_string();
        return packet;
    }

    std::vector<std::byte> serialize() const
    {
        Writer body;
        body.write<int32_t>(userid);
        body.write_string(reason);

        PacketHeader header;
        header.packet_id = ID;
        header.packet_size = static_cast<uint32_t>(sizeof(PacketHeader) + body.buffer().size());

        Writer writer;
        writer.write(header);
        writer.write_raw(body.buffer());
        return writer.buffer();
    }
};
using DisconnectServerPacket = S2C_Disconnect;

struct C2S_SetPosition
{
    static constexpr uint32_t ID = 3;

    double x = 0.0;
    double y = 0.0;
    bool facing_right = false;
    bool reset_velocity = false;

    static C2S_SetPosition deserialize(std::span<const std::byte> payload)
    {
        Reader reader(payload);
        C2S_SetPosition packet;
        packet.x = reader.read<double>();
        packet.y = reader.read<double>();
        packet.facing_right = reader.read<bool>();
        packet.reset_velocity = reader.read<bool>();
        return packet;
    }

    std::vector<std::byte> serialize() const
    {
        Writer body;
        body.write<double>(x);
        body.write<double>(y);
        body.write<bool>(facing_right);
        body.write<bool>(reset_velocity);

        PacketHeader header;
        header.packet_id = ID;
        header.packet_size = static_cast<uint32_t>(sizeof(PacketHeader) + body.buffer().size());

        Writer writer;
        writer.write(header);
        writer.write_raw(body.buffer());
        return writer.buffer();
    }
};
using SetPositionClientPacket = C2S_SetPosition;

struct S2C_SetPosition
{
    static constexpr uint32_t ID = 3;

    int32_t userid = 0;
    double x = 0.0;
    double y = 0.0;
    bool facing_right = false;
    bool reset_velocity = false;

    static S2C_SetPosition deserialize(std::span<const std::byte> payload)
    {
        Reader reader(payload);
        S2C_SetPosition packet;
        packet.userid = reader.read<int32_t>();
        packet.x = reader.read<double>();
        packet.y = reader.read<double>();
        packet.facing_right = reader.read<bool>();
        packet.reset_velocity = reader.read<bool>();
        return packet;
    }

    std::vector<std::byte> serialize() const
    {
        Writer body;
        body.write<int32_t>(userid);
        body.write<double>(x);
        body.write<double>(y);
        body.write<bool>(facing_right);
        body.write<bool>(reset_velocity);

        PacketHeader header;
        header.packet_id = ID;
        header.packet_size = static_cast<uint32_t>(sizeof(PacketHeader) + body.buffer().size());

        Writer writer;
        writer.write(header);
        writer.write_raw(body.buffer());
        return writer.buffer();
    }
};
using SetPositionServerPacket = S2C_SetPosition;

struct C2S_Move
{
    static constexpr uint32_t ID = 4;

    double x = 0.0;
    double y = 0.0;
    double vx = 0.0;
    double vy = 0.0;
    bool facing_right = false;

    static C2S_Move deserialize(std::span<const std::byte> payload)
    {
        Reader reader(payload);
        C2S_Move packet;
        packet.x = reader.read<double>();
        packet.y = reader.read<double>();
        packet.vx = reader.read<double>();
        packet.vy = reader.read<double>();
        packet.facing_right = reader.read<bool>();
        return packet;
    }

    std::vector<std::byte> serialize() const
    {
        Writer body;
        body.write<double>(x);
        body.write<double>(y);
        body.write<double>(vx);
        body.write<double>(vy);
        body.write<bool>(facing_right);

        PacketHeader header;
        header.packet_id = ID;
        header.packet_size = static_cast<uint32_t>(sizeof(PacketHeader) + body.buffer().size());

        Writer writer;
        writer.write(header);
        writer.write_raw(body.buffer());
        return writer.buffer();
    }
};
using MoveClientPacket = C2S_Move;

struct S2C_Move
{
    static constexpr uint32_t ID = 4;

    int32_t userid = 0;
    double x = 0.0;
    double y = 0.0;
    double vx = 0.0;
    double vy = 0.0;
    bool facing_right = false;

    static S2C_Move deserialize(std::span<const std::byte> payload)
    {
        Reader reader(payload);
        S2C_Move packet;
        packet.userid = reader.read<int32_t>();
        packet.x = reader.read<double>();
        packet.y = reader.read<double>();
        packet.vx = reader.read<double>();
        packet.vy = reader.read<double>();
        packet.facing_right = reader.read<bool>();
        return packet;
    }

    std::vector<std::byte> serialize() const
    {
        Writer body;
        body.write<int32_t>(userid);
        body.write<double>(x);
        body.write<double>(y);
        body.write<double>(vx);
        body.write<double>(vy);
        body.write<bool>(facing_right);

        PacketHeader header;
        header.packet_id = ID;
        header.packet_size = static_cast<uint32_t>(sizeof(PacketHeader) + body.buffer().size());

        Writer writer;
        writer.write(header);
        writer.write_raw(body.buffer());
        return writer.buffer();
    }
};
using MoveServerPacket = S2C_Move;

struct C2S_Attack
{
    static constexpr uint32_t ID = 5;


    static C2S_Attack deserialize([[maybe_unused]] std::span<const std::byte> payload)
    {
        return C2S_Attack{};
    }

    std::vector<std::byte> serialize() const
    {
        PacketHeader header;
        header.packet_id = ID;
        header.packet_size = static_cast<uint32_t>(sizeof(PacketHeader));

        Writer writer;
        writer.write(header);
        return writer.buffer();
    }
};
using AttackClientPacket = C2S_Attack;

struct S2C_Attack
{
    static constexpr uint32_t ID = 5;

    int32_t userid = 0;

    static S2C_Attack deserialize(std::span<const std::byte> payload)
    {
        Reader reader(payload);
        S2C_Attack packet;
        packet.userid = reader.read<int32_t>();
        return packet;
    }

    std::vector<std::byte> serialize() const
    {
        Writer body;
        body.write<int32_t>(userid);

        PacketHeader header;
        header.packet_id = ID;
        header.packet_size = static_cast<uint32_t>(sizeof(PacketHeader) + body.buffer().size());

        Writer writer;
        writer.write(header);
        writer.write_raw(body.buffer());
        return writer.buffer();
    }
};
using AttackServerPacket = S2C_Attack;

} // namespace Packet

#endif // __PACKETS_GENERATED_H__
